applications/posts/routes.py
from crypt import methods
from math import ceil
import os
import secrets
from socket import CAN_RAW
from time import time
from urllib import response
from flask import Blueprint, jsonify, render_template, request, current_app, abort
from flask_login import current_user, login_required
from applications.models import Post, Category, Users, Comment
from .utils import allowed_file
from werkzeug.utils import secure_filename
from applications.server import app
from applications.database import db
from datetime import datetime

posts = Blueprint("post", __name__)


@posts.route('/add_post', methods=['POST', 'GET'])
@login_required
def add_post():
    if request.method == 'GET':
        post_id = request.args.get("post_id")
        if post_id:
            post = db.session.query(Post).filter(Post.id == post_id).first()
            if post:
                return render_template('post/add_post.html', post=post)
        return render_template('post/add_post.html', post=None)
        
    elif request.method == 'POST':
        post_id = request.form['post_id']
        print("post_id", post_id)
        if post_id:
            post = db.session.query(Post).filter(Post.id == post_id).first()
            if post is None:
                post = Post()
        else:
            post = Post()

        post.title = request.form['title']
        post.summary = request.form['summary']
        post.content = request.form['content']
        post.source = request.form['source']
        post.user_id = current_user.id
        post.list_categories = []
        for category_id in request.form['category'].split(','):
            category = db.session.query(Category).filter(Category.id == category_id).first()
            print(category)
            post.list_categories.append(category)

        if 'files[]' in request.files:
            files = request.files.getlist('files[]')
            for file in files:
                if file and allowed_file(file.filename):
                    random_hex = secrets.token_hex(8)
                    _, f_ext = os.path.splitext(file.filename)
                    file.filename = random_hex + f_ext
                    uploads_dir = os.path.join(current_app.root_path, 'static/img/post', secure_filename(file.filename))
                    file.save(uploads_dir)
                    post.post_picture = file.filename

        db.session.add(post)
        db.session.commit()
        return jsonify({}), 200
    return jsonify({"error_message": "Hệ thống đang xảy ra lỗi, vui lòng liên hệ sau"}), 520

def get_top_view():
    end_date = datetime.now()
    start_date = datetime(end_date.year, end_date.month, 1, 0, 0, 0)
    top_post = []
    for post in db.session.query(Post)\
            .filter(Post.time >= start_date.timestamp(),
                    Post.time <= end_date.timestamp()).order_by(Post.views.desc()).limit(3).all():
        category = post.list_categories[0].__dict__
        post = post.__dict__
        # post['time'] = datetime.fromtimestamp(int(post['time'])).strftime("%d-%m-%Y")
        post['category'] = category
        top_post.append(post)
    return top_post

def get_top_like():
    end_date = datetime.now()
    start_date = datetime(end_date.year, end_date.month, 1, 0, 0, 0)
    top_post = []
    for post in db.session.query(Post)\
            .filter(Post.time >= start_date.timestamp(),
                    Post.time <= end_date.timestamp()).order_by(Post.liked.desc()).limit(5).all():
        timedelta = end_date - post.date_posted
        category = post.list_categories[0].__dict__
        post = post.__dict__
        # post['time'] = datetime.fromtimestamp(int(post['time'])).strftime("%d-%m-%Y")
        post['category'] = category
        top_post.append(post)
        if timedelta.days != 0:
            post['time_delta'] = f"{timedelta.days} ngày trước"
        elif timedelta.total_seconds()//3600 > 1:
            post['time_delta'] = f"{int(timedelta.total_seconds()//3600)} giờ trước"
        else:
            post['time_delta'] = f"{int(timedelta.total_seconds()//60)} phút trước"
    return top_post
    
def get_same_category(list_category):
    list_post = []
    result = []
    for category in list_category:
        # category = db.session.query(Category).filter(Category.id == category['id']).first()
        if len(category.posts.all()) >= 6:
            list_post = category.posts.all()[:6]
        else: list_post = category.posts.all()

        for post in list_post:
            post = post.__dict__
            post['category'] = category.category_name
            print(post['time'])
            post['time'] = datetime.fromtimestamp(post['time']).strftime("%d-%m-%Y")
            result.append(post)

        return result

@posts.route('/post/<int:post_id>', methods = ['GET'])
def post(post_id):
    post = db.session.query(Post).filter(Post.id == post_id).first()
    if post:

        # Get top6 same category
        same_category = get_same_category(post.list_categories)

        # Get category
        list_categories = []
        for category in post.list_categories:
            list_categories.append(category.__dict__)     
        post = post.__dict__

        # Get top3 view in day
        post["top_view"] = get_top_view()
        
        post["same_category"] = same_category
        # post['time'] = datetime.fromtimestamp(int(post['time'])).strftime("%d-%m-%Y %H:%M")
        post['list_categories'] = list_categories
        post['user_id'] = Users.query.get(int(post['user_id'])).__dict__
        return render_template('post/single.html', post=post, title=post['title'])
    else:
        abort(404)


def new_post():
    now = datetime.now()
    posts = db.session.query(Post).order_by(Post.time.desc()).limit(5).all()
    list_post = []
    for post in posts:
        timedelta = now - post.date_posted
        print(timedelta)
        list_category = [category.__dict__ for category in post.list_categories]
        post = post.__dict__ 
        post['category'] = list_category
        if timedelta.days != 0:
            post['time_delta'] = f"{timedelta.days} ngày trước"
        elif timedelta.total_seconds()//3600 > 1:
            post['time_delta'] = f"{int(timedelta.total_seconds()//3600)} giờ trước"
        else:
            post['time_delta'] = f"{int(timedelta.total_seconds()//60)} phút trước"
        list_post.append(post)
    return list_post

@posts.route("/category/<category_code>", methods=["GET"])
def category(category_code):
    page = request.args.get("page", 1, type=int)
    category = db.session.query(Category).filter(Category.category_code == category_code).first()
    
    if category is None:
        abort(404)

    all_post = category.posts.all()
    sort_view = sorted(all_post, key=lambda item: item.views)

    category = category.__dict__
    category["post"] = []
    # Slice summary
    for post in all_post[page*5 - 5: page*5]:
        post = post.__dict__
        post['time'] = datetime.fromtimestamp(post['time']).strftime("%d-%m-%Y")
        post["summary"] = post["summary"] if len(post["summary"].split(" ")) < 30 else " ".join(post["summary"].split(" ")[:30]) + " ..."
        category["post"].append(post)

    category["total_pages"] = ceil(len(all_post)/5)
    category["page"] = page
    category["top_view"] = [post.__dict__ for post in sort_view[:3]]
    category["new_post"] = new_post()

    return render_template('post/category.html', post=category)

@posts.route('/add_view', methods=["GET"])
def add_view():
    post_id = request.args.get("post_id")
    if post_id:
        post = db.session.query(Post).filter(Post.id == post_id).first()
        if post:
            post.views += 1
            db.session.commit()
            return jsonify({}), 200

@posts.route('/delete', methods=["GET"])
def delete():
    post_id = request.args.get("post_id")
    if post_id:
        post = db.session.query(Post).filter(Post.id==post_id).first()
        if post and post.user_id == current_user.id:
            db.session.delete(post)
            db.session.commit()
            return jsonify({}), 200
        return jsonify({"error_message": "Không tìm thấy bài viết hoặc bạn không phải tác giả bài viết"}), 520
    return jsonify({"error_message": "Hệ thống đang gặp sự cố, vui lòng thử lại sau"}), 520

@posts.route('/get_category', methods=['GET'])
def get_category():
    post_id = request.args.get("post_id")
    if post_id:
        post = db.session.query(Post).filter(Post.id == post_id).first()
        if post:
            category = post.list_categories
            return jsonify({"category": [item.id for item in category]}), 200
        return jsonify({"error_message": "Không tìm thấy bài viết"}), 200
    return jsonify({"error_message": "Tham số truyền vào sai hoặc thiếu"})

@posts.route('/get_all_posts', methods=["GET"])
def get_all_posts():
    page = request.args.get("page", 1, type=int)
    print(page)

    all_post = db.session.query(Post).order_by(Post.time.desc()).limit(5).offset(page*5-5).all()
    post = dict()
    list_post_render = []
    for post in all_post:
        post = post.__dict__
        post['time'] = datetime.fromtimestamp(post['time']).strftime("%d-%m-%Y")
        post["summary"] = post["summary"] if len(post["summary"].split(" ")) < 30 else " ".join(post["summary"].split(" ")[:30]) + " ..."
        list_post_render.append(post)

    print(list_post_render)
    post['render'] = list_post_render
    post['top_view'] = get_top_view()
    post['top_like'] = get_top_like()
    post['page'] = page
    post['total_pages'] = ceil(db.session.query(Post).count() / 5)

    return render_template('post/post.html', post=post)


@posts.route('/post_comment', methods=['POST'])
def post_comment():
    param = request.json
    name = param.get("name", None)
    email = param.get("email", None)
    comment = param.get("comment", None)
    post_id = param.get("post_id")
    reply_comment = int(param.get("reply_comment", 0))

applications/templates/post/category.html
{% extends 'layout.html' %}
{% block title %}
    <title>{{ post.category_name }}</title>
{% endblock %}
{% block content %}
<!-- Breaking News Start -->
<div class="container-fluid mt-5 mb-3 pt-3">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-12">
                <div class="d-flex justify-content-between">
                    <div class="section-title border-right-0 mb-0" style="width: 180px;">
                        <h4 class="m-0 text-uppercase font-weight-bold">Xu hướng</h4>
                    </div>
                    <div class="owl-carousel tranding-carousel position-relative d-inline-flex align-items-center bg-white border border-left-0"
                        style="width: calc(100% - 180px); padding-right: 100px;">
                        {% for item in post.top_view %}
                            <div class="text-truncate"><a class="text-secondary text-uppercase font-weight-semi-bold" href="{{ url_for('post.post', post_id=item.id) }}">{{ item.title }}</a></div>
                        {% endfor %}
                        <!-- <div class="text-truncate"><a class="text-secondary text-uppercase font-weight-semi-bold" href="">Lorem ipsum dolor sit amet elit. Proin interdum lacus eget ante tincidunt, sed faucibus nisl sodales</a></div> -->
                        <!-- <div class="text-truncate"><a class="text-secondary text-uppercase font-weight-semi-bold" href="">Lorem ipsum dolor sit amet elit. Proin interdum lacus eget ante tincidunt, sed faucibus nisl sodales</a></div> -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Breaking News End -->


<!-- News With Sidebar Start -->
<div class="container-fluid">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="position-relative mb-3">
                    
                    <div class="bg-white border-top-0 p-4">
                        <a class="badge badge-primary text-uppercase font-weight-semi-bold p-1 mr-2" href="" style="font-size: 18px;">{{ post.category_name }}</a>
                        {% for post in post.post %}
                        <div class="bg-white border-top p-3">
                            <a class="h6 m-0 text-secondary text-uppercase font-weight-bold" href="{{ url_for('post.post', post_id=post.id) }}" style="overflow: auto;">{{ post.title }}</a>
                                <div class="d-flex align-items-center bg-white mb-3" style="height: 110px;">
                                    <img class="img-fluid" src="{{ url_for('static', filename='/img/post/' + post.post_picture) }}" alt="" style="width: 110px; height: 110px;">
                                    <div class="w-100 h-100 px-3 d-flex flex-column justify-content-center">
                                        <div class="mb-2">
                                            <h6>{{ post.time }}</h6>
                                            <p style="overflow: hidden;">{{ post.summary }}</p>
                                        </div>
                                    </div>
                                </div>
                        </div>
                        {% endfor %}
                        <div style="display: flex; justify-content: flex-end">
                            <div class="pagination" style="margin-left:auto; margin-right:0;">
                                <a href="{{ url_for('post.category', page=post.page-1, category_code=post.category_code) }}">&laquo;</a>
                                    {% for i in range(1, post.total_pages+1) %}
                                        {% if i == post.page %}
                                            <a class="active" href="{{ url_for('post.category', page=i, category_code=post.category_code) }}">{{ i }}</a>
                                        {% elif ((i+1 == post.page) or (i-1 == post.page) or (i==1) or (i==post.total_pages)) %}
                                            <a href="{{ url_for('post.category', page=i, category_code=post.category_code) }}">{{ i }}</a>
                                        {% elif ((i+2 == post.page) or (i-2 == post.page)) %}
                                            <a href="">...</a>
                                        {% endif %}
                                            
                                    {% endfor %}
                                <a href="{{ url_for('post.category', page=post.page+1, category_code=post.category_code) }}">&raquo;</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <!-- Social Follow Start -->
                <div class="mb-3">
                    <div class="section-title mb-0">
                        <h4 class="m-0 text-uppercase font-weight-bold">Theo dõi chúng tôi</h4>
                    </div>
                    <div class="bg-white border border-top-0 p-3">
                        <a href="" class="d-block w-100 text-white text-decoration-none mb-3" style="background: #39569E;">
                            <i class="fab fa-facebook-f text-center py-4 mr-3" style="width: 65px; background: rgba(0, 0, 0, .2);"></i>
                            <span class="font-weight-medium">12,345 Fans</span>
                        </a>
                        <a href="" class="d-block w-100 text-white text-decoration-none mb-3" style="background: #52AAF4;">
                            <i class="fab fa-twitter text-center py-4 mr-3" style="width: 65px; background: rgba(0, 0, 0, .2);"></i>
                            <span class="font-weight-medium">12,345 Theo dõi</span>
                        </a>
                        <a href="" class="d-block w-100 text-white text-decoration-none mb-3" style="background: #0185AE;">
                            <i class="fab fa-linkedin-in text-center py-4 mr-3" style="width: 65px; background: rgba(0, 0, 0, .2);"></i>
                            <span class="font-weight-medium">12,345 Liên kết</span>
                        </a>
                        <a href="" class="d-block w-100 text-white text-decoration-none mb-3" style="background: #C8359D;">
                            <i class="fab fa-instagram text-center py-4 mr-3" style="width: 65px; background: rgba(0, 0, 0, .2);"></i>
                            <span class="font-weight-medium">12,345 Theo dõi</span>
                        </a>
                        <a href="" class="d-block w-100 text-white text-decoration-none mb-3" style="background: #DC472E;">
                            <i class="fab fa-youtube text-center py-4 mr-3" style="width: 65px; background: rgba(0, 0, 0, .2);"></i>
                            <span class="font-weight-medium">12,345 Đăng ký</span>
                        </a>
                        <a href="" class="d-block w-100 text-white text-decoration-none" style="background: #055570;">
                            <i class="fab fa-vimeo-v text-center py-4 mr-3" style="width: 65px; background: rgba(0, 0, 0, .2);"></i>
                            <span class="font-weight-medium">12,345 Theo dõi</span>
                        </a>
                    </div>
                </div>
                <!-- Social Follow End -->

                <!-- Ads Start -->
                <div class="mb-3">
                    <div class="section-title mb-0">
                        <h4 class="m-0 text-uppercase font-weight-bold">Quảng Cáo</h4>
                    </div>
                    <div class="bg-white text-center border border-top-0 p-3">
                        <a href=""><img class="img-fluid" src="{{ url_for('static', filename='/img/800x500.png') }}" alt=""></a>
                    </div>
                </div>
                <!-- Ads End -->

                <!-- Popular News Start -->
                <div class="mb-3">
                    <div class="section-title mb-0">
                        <h4 class="m-0 text-uppercase font-weight-bold">Bài viết mới</h4>
                    </div>
                    <div class="bg-white border border-top-0 p-3">
                        {% for post in post.new_post %}
                            {% for category in post.category %}
                            <a class="badge badge-primary text-uppercase font-weight-semi-bold p-1 mr-2" href="{{ url_for('post.category', category_code=category.category_code) }}">{{ category.category_name }}</a>
                            {% endfor %}
                            <div class="d-flex align-items-top bg-white mb-3 mt-1" style="height: 110px;">
                                <img class="img-fluid" src="{{ url_for('static', filename='/img/post/' + post.post_picture) }}" alt="" style="width: 110px; height: 110px;">
                                <div class="w-100 h-100 px-3 d-flex flex-column border-bottom">
                                    <div class="mb-2">
                                        <a class="text-body" href="" ><small>{{ post.time_delta }}</small></a>
                                    </div>
                                    <a class="h6 m-0 text-secondary text-uppercase font-weight-bold" href="{{ url_for('post.post', post_id=post.id) }}" style="overflow: auto;">{{ post.title }}</a>
                                </div>
                            </div>
                            
                        {% endfor %}
                    </div>
                </div>
                <!-- Popular News End -->

                <!-- Newsletter Start -->
                <div class="mb-3">
                    <div class="section-title mb-0">
                        <h4 class="m-0 text-uppercase font-weight-bold">Thông báo</h4>
                    </div>
                    <div class="bg-white text-center border border-top-0 p-3">
                        <p>Đăng ký để nhận thông báo về bài đăng mới nhất</p>
                        <div class="input-group mb-2" style="width: 100%;">
                            <input type="text" class="form-control form-control-lg" placeholder="Email của bạn">
                            <div class="input-group-append">
                                <button class="btn btn-primary font-weight-bold px-3">Đăng ký</button>
                            </div>
                        </div>
                        <small>Email thu thập nhằm mục đích phát triển blog tốt hơn không phải vì mục đích thương mại</small>
                    </div>
                </div>
                <!-- Newsletter End -->
            </div>
        </div>
    </div>
</div>
<!-- News With Sidebar End -->
{% endblock %}

applications/templates/post/post.html
{% extends 'layout.html' %}
{% block title %}
    <title>Bài viết - Trang {{ post.page }}</title>
{% endblock %}
{% block content %}
<!-- Breaking News Start -->
<div class="container-fluid mt-5 mb-3 pt-3">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-12">
                <div class="d-flex justify-content-between">
                    <div class="section-title border-right-0 mb-0" style="width: 180px;">
                        <h4 class="m-0 text-uppercase font-weight-bold">Xu hướng</h4>
                    </div>
                    <div class="owl-carousel tranding-carousel position-relative d-inline-flex align-items-center bg-white border border-left-0"
                        style="width: calc(100% - 180px); padding-right: 100px;">
                        {% for item in post.top_view %}
                            <div class="text-truncate"><a class="text-secondary text-uppercase font-weight-semi-bold" href="{{ url_for('post.post', post_id=item.id) }}">{{ item.title }}</a></div>
                        {% endfor %}
                        <!-- <div class="text-truncate"><a class="text-secondary text-uppercase font-weight-semi-bold" href="">Lorem ipsum dolor sit amet elit. Proin interdum lacus eget ante tincidunt, sed faucibus nisl sodales</a></div> -->
                        <!-- <div class="text-truncate"><a class="text-secondary text-uppercase font-weight-semi-bold" href="">Lorem ipsum dolor sit amet elit. Proin interdum lacus eget ante tincidunt, sed faucibus nisl sodales</a></div> -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Breaking News End -->


<!-- News With Sidebar Start -->
<div class="container-fluid">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="position-relative mb-3">
                    
                    <div class="bg-white border-top-0 p-4">
                        {% for post in post.render %}
                        <div class="bg-white border-top p-3">
                            <a class="h6 m-0 text-secondary text-uppercase font-weight-bold" href="{{ url_for('post.post', post_id=post.id) }}" style="overflow: auto;">{{ post.title }}</a>
                                <div class="d-flex align-items-center bg-white mb-3" style="height: 110px;">
                                    <img class="img-fluid" src="{{ url_for('static', filename='/img/post/' + post.post_picture) }}" alt="" style="width: 110px; height: 110px;">
                                    <div class="w-100 h-100 px-3 d-flex flex-column justify-content-center">
                                        <div class="mb-2">
                                            <h6>{{ post.time }}</h6>
                                            <p style="overflow: hidden;">{{ post.summary }}</p>
                                        </div>
                                    </div>
                                </div>
                        </div>
                        {% endfor %}
                        <div style="display: flex; justify-content: flex-end">
                            <div class="pagination" style="margin-left:auto; margin-right:0;">
                                <a href="{{ url_for('post.get_all_posts', page=post.page-1) }}">&laquo;</a>
                                    {% for i in range(1, post.total_pages+1) %}
                                        {% if i == post.page %}
                                            <a class="active" href="{{ url_for('post.get_all_posts', page=i) }}">{{ i }}</a>
                                        {% elif ((i+1 == post.page) or (i-1 == post.page) or (i==1) or (i==post.total_pages)) %}
                                            <a href="{{ url_for('post.get_all_posts', page=i) }}">{{ i }}</a>
                                        {% elif ((i+2 == post.page) or (i-2 == post.page)) %}
                                            <a href="">...</a>
                                        {% endif %}
                                            
                                    {% endfor %}
                                <a href="{{ url_for('post.get_all_posts', page=post.page+1) }}">&raquo;</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <!-- Social Follow Start -->
                <div class="mb-3">
                    <div class="section-title mb-0">
                        <h4 class="m-0 text-uppercase font-weight-bold">Theo dõi chúng tôi</h4>
                    </div>
                    <div class="bg-white border border-top-0 p-3">
                        <a href="" class="d-block w-100 text-white text-decoration-none mb-3" style="background: #39569E;">
                            <i class="fab fa-facebook-f text-center py-4 mr-3" style="width: 65px; background: rgba(0, 0, 0, .2);"></i>
                            <span class="font-weight-medium">12,345 Fans</span>
                        </a>
                        <a href="" class="d-block w-100 text-white text-decoration-none mb-3" style="background: #52AAF4;">
                            <i class="fab fa-twitter text-center py-4 mr-3" style="width: 65px; background: rgba(0, 0, 0, .2);"></i>
                            <span class="font-weight-medium">12,345 Theo dõi</span>
                        </a>
                        <a href="" class="d-block w-100 text-white text-decoration-none mb-3" style="background: #0185AE;">
                            <i class="fab fa-linkedin-in text-center py-4 mr-3" style="width: 65px; background: rgba(0, 0, 0, .2);"></i>
                            <span class="font-weight-medium">12,345 Liên kết</span>
                        </a>
                        <a href="" class="d-block w-100 text-white text-decoration-none mb-3" style="background: #C8359D;">
                            <i class="fab fa-instagram text-center py-4 mr-3" style="width: 65px; background: rgba(0, 0, 0, .2);"></i>
                            <span class="font-weight-medium">12,345 Theo dõi</span>
                        </a>
                        <a href="" class="d-block w-100 text-white text-decoration-none mb-3" style="background: #DC472E;">
                            <i class="fab fa-youtube text-center py-4 mr-3" style="width: 65px; background: rgba(0, 0, 0, .2);"></i>
                            <span class="font-weight-medium">12,345 Đăng ký</span>
                        </a>
                        <a href="" class="d-block w-100 text-white text-decoration-none" style="background: #055570;">
                            <i class="fab fa-vimeo-v text-center py-4 mr-3" style="width: 65px; background: rgba(0, 0, 0, .2);"></i>
                            <span class="font-weight-medium">12,345 Theo dõi</span>
                        </a>
                    </div>
                </div>
                <!-- Social Follow End -->

                <!-- Ads Start -->
                <div class="mb-3">
                    <div class="section-title mb-0">
                        <h4 class="m-0 text-uppercase font-weight-bold">Quảng Cáo</h4>
                    </div>
                    <div class="bg-white text-center border border-top-0 p-3">
                        <a href=""><img class="img-fluid" src="{{ url_for('static', filename='/img/800x500.png') }}" alt=""></a>
                    </div>
                </div>
                <!-- Ads End -->

                <!-- Popular News Start -->
                <div class="mb-3">
                    <div class="section-title mb-0">
                        <h4 class="m-0 text-uppercase font-weight-bold">Nổi bật</h4>
                    </div>
                    <div class="bg-white border border-top-0 p-3">
                        {% for post in post.top_like %}
                            <a class="badge badge-primary text-uppercase font-weight-semi-bold p-1 mr-2" href="{{ url_for('post.category', category_code=post.category.category_code) }}">{{ post.category.category_name }}</a>
                            <div class="d-flex align-items-top bg-white mb-3 mt-1" style="height: 110px;">
                                <img class="img-fluid" src="{{ url_for('static', filename='/img/post/' + post.post_picture) }}" alt="" style="width: 110px; height: 110px;">
                                <div class="w-100 h-100 px-3 d-flex flex-column border-bottom">
                                    <div class="mb-2">
                                        <a class="text-body" href="" ><small>{{ post.time_delta }}</small></a>
                                    </div>
                                    <a class="h6 m-0 text-secondary text-uppercase font-weight-bold" href="{{ url_for('post.post', post_id=post.id) }}" style="overflow: auto;">{{ post.title }}</a>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
                <!-- Popular News End -->

                <!-- Newsletter Start -->
                <div class="mb-3">
                    <div class="section-title mb-0">
                        <h4 class="m-0 text-uppercase font-weight-bold">Thông báo</h4>
                    </div>
                    <div class="bg-white text-center border border-top-0 p-3">
                        <p>Đăng ký để nhận thông báo về bài đăng mới nhất</p>
                        <div class="input-group mb-2" style="width: 100%;">
                            <input type="text" class="form-control form-control-lg" placeholder="Email của bạn">
                            <div class="input-group-append">
                                <button class="btn btn-primary font-weight-bold px-3">Đăng ký</button>
                            </div>
                        </div>
                        <small>Email thu thập nhằm mục đích phát triển blog tốt hơn không phải vì mục đích thương mại</small>
                    </div>
                </div>
                <!-- Newsletter End -->
            </div>
        </div>
    </div>
</div>
<!-- News With Sidebar End -->
{% endblock %}